/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface StencilConsumer {
    'renderer': Function;
  }
  interface StencilProvider {
    'STENCIL_CONTEXT': { [key: string]: any };
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  const HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLStencilConsumerElement extends Components.StencilConsumer, HTMLStencilElement {}
  const HTMLStencilConsumerElement: {
    prototype: HTMLStencilConsumerElement;
    new (): HTMLStencilConsumerElement;
  };

  interface HTMLStencilProviderElement extends Components.StencilProvider, HTMLStencilElement {}
  const HTMLStencilProviderElement: {
    prototype: HTMLStencilProviderElement;
    new (): HTMLStencilProviderElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'stencil-consumer': HTMLStencilConsumerElement;
    'stencil-provider': HTMLStencilProviderElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {}
  interface StencilConsumer {
    'renderer'?: Function;
  }
  interface StencilProvider {
    'STENCIL_CONTEXT'?: { [key: string]: any };
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'stencil-consumer': StencilConsumer;
    'stencil-provider': StencilProvider;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'stencil-consumer': LocalJSX.StencilConsumer & JSXBase.HTMLAttributes<HTMLStencilConsumerElement>;
      'stencil-provider': LocalJSX.StencilProvider & JSXBase.HTMLAttributes<HTMLStencilProviderElement>;
    }
  }
}


